name: yogita
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - nodejs
  - ipywidgets
  - pandas
  - dask
  - dask-image
  - dask-labextension
  - matplotlib
  - matplotlib-scalebar
  - seaborn
  - tqdm
  - openpyxl  
  - tabulate